name: Terraform Plan & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan -var="project_id=$PROJECT_ID" \
            -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: plan
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve tfplan

      - name: Output Cloud Run URL
        run: echo "Cloud Run service deployed at $(terraform output cloud_run_url)"
